apiVersion: v1
data:
    name: ENC[AES256_GCM,data:FXgL614=,iv:dw9ZbNxtn6EKXfgk7JY7sJAl2ItRxVOEjysX5AMzbZI=,tag:2/typmtRVDsafcUWoJHldw==,type:str]
kind: Secret
metadata:
    name: name
sops:
    lastmodified: "2025-05-14T17:23:27Z"
    mac: ENC[AES256_GCM,data:B4A3y9kX6tFjCTS2IM/RTyXWGQMOnrQIb+NrFJba6bFfcOqY9VeN02O2mm+KN89T+agnonztMN1jr83XuPewCedkCJKIsygmnUXhasUOiTjTrez9gSc+urCJdFQSTe7/S82e3aqHLFvome7C/ZbP/Z9I6fcUElR5aTIzS6lOenU=,iv:l9i3EVR6a5h3dEiIbswO7isgl+hSO4QScDaPl4OP4VM=,tag:r8CtfcW4fHFQRRfW90zHHg==,type:str]
    pgp:
        - created_at: "2025-05-14T17:22:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hIwD4vMQb0uHH64BBACawGRBQlctzOAYdnU1kuOrwBhrJMQEDBSlkO4/A2DfhkqM
            yL+T4CLm00apUE6wiU/xKHxXkJFapGYY7xVfPYhTUgSl4tkpngG+EutV+Dfyh3rA
            UkBKtN25xk1zfB67DTe7JFPE+trtL2/xBdn3aBF9wERK2EiHidnWZvBw4zubhdRm
            AQkCEEHIBWMjGe5kKbb9xJUUdO4nlUcO71Ns1Jq3CqgTrO+Kinw37M04DGv54bLX
            Q6lqPZ1nbsdT6IYo981P66WCwBMrKuL3oY6CNzMeehQd9cp0uIvnwSUqZ2kTYErX
            PFWf6dXc
            =PDOA
            -----END PGP MESSAGE-----
          fp: 5B7B221B4AC823B712C2E576C52AF954DED0E907
    encrypted_regex: ^(users|data|stringData)$
    version: 3.10.2
