resources:
  - ./resources.yaml

helmCharts:
  - name: karpenter
    repo: oci://public.ecr.aws/karpenter
    version: 1.4.0
    releaseName: karpenter
    namespace: karpenter
    includeCRDs: true
    valuesFile: values.yaml
