dnsPolicy: Default
settings:
  clusterName: experimental-cluster
  interruptionQueue: experimental-cluster
controller:
  env: [{"name": "AWS_REGION", "value": "ap-southeast-1"}]
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
serviceAccount:
  create: false
  name: karpenter
