networks: 
  mynetwork:
    name: mynetwork
    attachable: true    

volumes:
    postgres_data:

services:
  
  postgres:
      image: postgres:12.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432
      networks:
       - mynetwork

        
  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      # KC_HOSTNAME: localhost
      # KC_HOSTNAME_PORT: 8080
      # KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 3333:8080
    depends_on:
      - postgres
    networks:
      - mynetwork


  nginx:
    image: fresh-nginx
    ports:
      - 80:80
    networks:
      - mynetwork
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
