resources:
  - ./resources.yaml

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.12.2
    releaseName: ingress-nginx
    namespace: ingress-nginx
    includeCRDs: true
    valuesFile: values.yaml
