apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nhphat1997@gmail.com
    # Reuse the existing account key instead of generating a new one.
    # Refs: https://cert-manager.io/docs/configuration/acme/#reusing-an-acme-account
    disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
