resources:
  - ./resources.yaml

generators:
  - ./generators.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.17.2
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
    valuesFile: values.yaml
